# Generated by Django 4.2 on 2024-12-02 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_doctoreducation_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctoreducation',
            name='completion_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctorexperience',
            name='period_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctorexperience',
            name='period_to',
            field=models.DateField(blank=True, null=True),
        ),
    ]
