# Generated by Django 4.2 on 2024-12-02 14:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0005_alter_doctorlicensing_license_issuing_authority'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctoravailability',
            name='day_of_week',
            field=models.IntegerField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], null=True),
        ),
        migrations.AddField(
            model_name='doctoravailability',
            name='doctor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='doctoravailability',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctoravailability',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='doctoravailability',
            unique_together={('doctor', 'day_of_week')},
        ),
        migrations.RemoveField(
            model_name='doctoravailability',
            name='available_for_emergency',
        ),
        migrations.RemoveField(
            model_name='doctoravailability',
            name='consultation_days_hours',
        ),
        migrations.RemoveField(
            model_name='doctoravailability',
            name='user',
        ),
        migrations.RemoveField(
            model_name='doctoravailability',
            name='virtual_consultation_availability',
        ),
    ]
