# Generated by Django 4.2 on 2024-12-02 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_doctoravailability_day_of_week_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctoravailability',
            options={'verbose_name_plural': 'Doctor Availability'},
        ),
        migrations.AlterUniqueTogether(
            name='doctoravailability',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='doctoravailability',
            name='friday_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='doctoravailability',
            name='friday_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctoravailability',
            name='friday_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctoravailability',
            name='monday_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='doctoravailability',
            name='monday_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctoravailability',
            name='monday_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctoravailability',
            name='saturday_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='doctoravailability',
            name='saturday_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctoravailability',
            name='saturday_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctoravailability',
            name='sunday_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='doctoravailability',
            name='sunday_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctoravailability',
            name='sunday_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctoravailability',
            name='thursday_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='doctoravailability',
            name='thursday_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctoravailability',
            name='thursday_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctoravailability',
            name='tuesday_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='doctoravailability',
            name='tuesday_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctoravailability',
            name='tuesday_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctoravailability',
            name='wednesday_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='doctoravailability',
            name='wednesday_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctoravailability',
            name='wednesday_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='doctoravailability',
            name='day_of_week',
        ),
        migrations.RemoveField(
            model_name='doctoravailability',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='doctoravailability',
            name='start_time',
        ),
    ]
