# Generated by Django 4.2 on 2024-12-03 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_doctoravailability_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctoreducation',
            name='specialization',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
