# Generated by Django 4.2 on 2024-12-03 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_panel', '0001_initial'),
        ('accounts', '0008_alter_doctoreducation_specialization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctoreducation',
            name='specialization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doctor_panel.department'),
        ),
    ]
