# Generated by Django 4.2 on 2024-12-06 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_appointment_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_remarks', models.TextField(blank=True, null=True)),
                ('prescribed_drugs', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prescription_date', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prescription', to='appointments.appointment')),
            ],
            options={
                'verbose_name_plural': 'Prescriptions',
            },
        ),
    ]
